[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    cache-control = "public,max-age=0,must-revalidate"
